name: Training & Docker Build Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install MLflow & Dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn matplotlib seaborn

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run MLflow Project (Training)
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          cd MLProject
          mlflow run . --no-conda 

      - name: Build & Push Docker Image (Advance Requirement)
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/rizalafandee/Liver_Prediction.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # 1. Ambil Run ID terakhir dari eksperimen
          LAST_RUN_ID=$(python -c "import mlflow; mlflow.set_tracking_uri('$MLFLOW_TRACKING_URI'); print(mlflow.search_runs(experiment_names=['Liver_Prediction_CI'], order_by=['start_time DESC']).iloc[0].run_id)")
          
          echo "Building Docker for Run ID: $LAST_RUN_ID"
          
          # 2. Build Docker Image menggunakan MLflow
          mlflow models build-docker \
            -m "runs:/$LAST_RUN_ID/model" \
            -n "${{ secrets.DOCKER_USERNAME }}/liver-prediction-model:latest" \
            --enable-mlserver

          # 3. Push ke Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/liver-prediction-model:latest
