name: CI MLflow Liver Prediction

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# IZIN WAJIB: Agar Bot boleh melakukan 'git push'
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
       
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Pasang semua library di sini agar tersedia untuk --env-manager=local
          pip install mlflow==2.19.0 pandas scikit-learn matplotlib seaborn
          
      # 1. RUN TRAINING
      - name: Run mlflow project
        run: |
          # Tambahkan --env-manager=local agar dia tidak mencoba membuat conda sendiri
          mlflow run MLProject --env-manager=local
       
      # 2. PUSH ARTIFACTS KE GITHUB REPO
      - name: Commit and Push Artifacts
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Masuk ke folder MLProject karena artifacts ada di sana
          cd MLProject
          
          # Cek apakah folder benar-benar ada
          ls -d artifacts/ || echo "Folder artifacts belum tercipta"
          
          # Tambahkan semua perubahan
          git add .
          
          # Commit & Push
          git commit -m "Auto-update: Training Artifacts [skip ci]" || echo "No changes to commit"
          git push

      # 3. DOCKER BUILD & PUSH
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "liver-model" 

      - name: Push Docker Image
        run: |
          docker tag liver-model ${{ secrets.DOCKER_USERNAME }}/liver-model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/liver-model:latest
