name: CI MLflow Liver Prediction

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
       
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0
          
      # 1. RUN TRAINING (Modelling)
      - name: Run mlflow project
        run: |
          # Ini akan menjalankan modelling.py dengan parameter default
          mlflow run MLProject --env-manager=local 
       
      # 2. AMBIL RUN_ID TERAKHIR
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"
          
      # 3. INSTALL LIB GOOGLE (Untuk script upload)
      - name: Install Python dependencies for GDrive
        run: |
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
        
      # 4. UPLOAD KE GDRIVE
      - name: Upload to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }} 
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }} 
        run: |
          # Memanggil script upload Python
          python MLProject/upload_to_gdrive.py

      # 5. DOCKER BUILD & PUSH (Sesuai Run ID)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "liver-model" 

      - name: Tag and Push Docker Image
        run: |
          docker tag liver-model ${{ secrets.DOCKER_HUB_USERNAME }}/liver-model:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/liver-model:latest
